[build]
  # Directory where your build command outputs the site
  publish = "dist"  
  # Build command (adjust if using React, Vite, or Next.js)
  command = "npm run build"

  # If your project is inside a subfolder, uncomment and set this
  # base = "frontend"

[dev]
  # Local dev settings for `netlify dev`
  command = "npm run dev"
  port = 8888
  targetPort = 5173   # Vite default; adjust if different

[functions]
  # Folder for Netlify serverless functions
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
